### ISSUE TITLE
pip install failed on windows , python 3.10.10

### ISSUE THREAD

**Issue by nogakertes** [NOhs/affine_transform_nd#35]
Hi, 
Thanks for your response in [here](https://github.com/NOhs/affine_transform_nd/issues/27)

I followed your suggestions and did the following things:
1. uninstalled the cmake python package.
1. download cmake from here: https://cmake.org/download/
2. add it the PATH (C:\Program Files\CMake\bin)
3. run pip install again and got the following error:

Collecting affine-transform
  Using cached affine_transform-0.3.2.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from affine-transform) (1.23.5)
Requirement already satisfied: mgen in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from affine-transform) (1.2.1)
Requirement already satisfied: setuptools-scm in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from affine-transform) (7.1.0)
Requirement already satisfied: pbr in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from mgen->affine-transform) (5.11.1)
Requirement already satisfied: packaging>=20.0 in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from setuptools-scm->affine-transform) (23.1)
Requirement already satisfied: setuptools in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from setuptools-scm->affine-transform) (67.7.2)
Requirement already satisfied: typing-extensions in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from setuptools-scm->affine-transform) (4.4.0)
Requirement already satisfied: tomli>=1.0.0 in c:\users\nogak\miniconda3\envs\dti_project\lib\site-packages (from setuptools-scm->affine-transform) (2.0.1)
Building wheels for collected packages: affine-transform
  Building wheel for affine-transform (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for affine-transform (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [139 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\affine_transform
      copying affine_transform\affine_transform.py -> build\lib.win-amd64-cpython-310\affine_transform
      copying affine_transform\__init__.py -> build\lib.win-amd64-cpython-310\affine_transform
      copying affine_transform\version.txt -> build\lib.win-amd64-cpython-310\affine_transform
      running build_ext
      <string>:29: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      -- Building for: Visual Studio 17 2022
      -- The C compiler identification is MSVC 19.34.31937.0
      -- The CXX compiler identification is MSVC 19.34.31937.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - broken
      CMake Error at C:/Users/nogak/AppData/Local/Temp/pip-build-env-2ni2hpjc/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: C:/Users/nogak/AppData/Local/Temp/pip-install-krz0k8qt/affine-transform_e25f18aaf3054035912ebbf714671681/build/temp.win-amd64-cpython-310/Release/CMakeFiles/CMakeScratch/TryCompile-3kgrbd

          Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_48e76.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.4.1+9a89d02ff for .NET Framework
          Build started 14/05/2023 19:25:33.
          Project "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj" on node 1 (default targets).
          PrepareForBuild:
            Creating directory "cmTC_48e76.dir\Debug\".
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
            Creating directory "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\Debug\".
            Creating directory "cmTC_48e76.dir\Debug\cmTC_48e76.tlog\".
          InitializeBuildStatus:
            Creating "cmTC_48e76.dir\Debug\cmTC_48e76.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
          ClCompile:
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_48e76.dir\Debug\\" /Fd"cmTC_48e76.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\testCCompiler.c"
            Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31937 for x64
            testCCompiler.c
            Copyright (C) Microsoft Corporation.  All rights reserved.
            cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_48e76.dir\Debug\\" /Fd"cmTC_48e76.dir\Debug\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\testCCompiler.c"
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.dir\Debug\cmTC_48e76.tlog'. [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          Done Building Project "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj" (default targets) -- FAILED.

          Build FAILED.

          "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj" (default target) (1) ->
          (PrepareForBuild target) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(527,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]

          "C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj" (default target) (1) ->
          (ClCompile target) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.dir\Debug\cmTC_48e76.tlog'. [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(703,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\nogak\AppData\Local\Temp\pip-install-krz0k8qt\affine-transform_e25f18aaf3054035912ebbf714671681\build\temp.win-amd64-cpython-310\Release\CMakeFiles\CMakeScratch\TryCompile-3kgrbd\cmTC_48e76.vcxproj]

              1 Warning(s)
              1 Error(s)

          Time Elapsed 00:00:00.41

        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:2 (project)

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\nogak\miniconda3\envs\DTI_project\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\nogak\miniconda3\envs\DTI_project\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\nogak\miniconda3\envs\DTI_project\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 111, in <module>
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\normal\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\nogak\AppData\Local\Temp\pip-build-env-2ni2hpjc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 36, in run
        File "<string>", line 67, in build_extension
        File "C:\Users\nogak\miniconda3\envs\DTI_project\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\nogak\\AppData\\Local\\Temp\\pip-install-krz0k8qt\\affine-transform_e25f18aaf3054035912ebbf714671681', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:/Users/nogak/AppData/Local/Temp/pip-install-krz0k8qt/affine-transform_e25f18aaf3054035912ebbf714671681/build/lib.win-amd64-cpython-310/affine_transform', '-DPYTHON_EXECUTABLE=C:\\Users\\nogak\\miniconda3\\envs\\DTI_project\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:/Users/nogak/AppData/Local/Temp/pip-install-krz0k8qt/affine-transform_e25f18aaf3054035912ebbf714671681/build/lib.win-amd64-cpython-310/affine_transform', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for affine-transform
Failed to build affine-transform
ERROR: Could not build wheels for affine-transform, which is required to install pyproject.toml-based projects

Thanks!

**Comment by NOhs** [comment]
Sorry for not replying to your issue so far. I tried to rework the package setup to hopefully be more robust and work on all major OSs (Win, Linux, OSX (with limitations)).

**Comment by NOhs** [comment]
I will close the issue for now. Should the error you are seeing persist, feel free to comment here and we can re-open this issue.
